[rewrite_local]
^https://screen-lock\.sm-check\.com/ url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/buding/buding.js

[MITM]
hostname = screen-lock.sm-check.com
